apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo-repo
  namespace: flux-system
spec:
  url: https://stefanprodan.github.io/podinfo
  interval: 1m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo-repo
        namespace: flux-system
      version: "5.2.0"
  interval: 1m
  install:
    remediation:
      retries: 30
  values:
    replicaCount: 2